name: 'intermediate branch automations'
description: 'automate merge and pull request creation in intermediate branch'
author: 'Benedict Steven'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  SLACK_WEBHOOK_URL:
    description: 'Slack webhook'
    required: true
  DESTINATION_BRANCH:
    description: 'destination branch for pushing new changes'
    required: true
  TARGET_BRANCH:
    description: 'target branch'
    required: true

runs:
  using: 'node16'
  main: 'actions/index.js'

branding:
  icon: 'package'
  color: 'gray-dark'