name: on pr to default branch

on:
   push:
     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm install

      - name: Build
        run: npm run build

      - name: eod actions
        uses: ./
        with: 
          GITHUB_TOKEN: ${{secrets.TOKEN}}
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          # SLACK_WEBHOOK_REVIEW_URL: ${{secrets.SLACK_WEBHOOK_REVIEW_URL}}
          TARGET_BRANCH: main
          DESTINATION_BRANCH: develop

      - uses: actions/checkout@v2
        with:
          ref: develop

      #  push changes to develop
      - name: update develop branch
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }}
          git add package.json
          git add changelog.md
          git commit -m "Skip CI"
          git push